//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservations.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reservations.Core.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite.
        /// </summary>
        public static string AddFavorite {
            get {
                return ResourceManager.GetString("AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Alphabetic Ascending.
        /// </summary>
        public static string AlphabeticAscending {
            get {
                return ResourceManager.GetString("AlphabeticAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Alphabetic Descending.
        /// </summary>
        public static string AlphabeticDescending {
            get {
                return ResourceManager.GetString("AlphabeticDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation List.
        /// </summary>
        public static string BtnReservationList {
            get {
                return ResourceManager.GetString("BtnReservationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact name exit.
        /// </summary>
        public static string ContactExist {
            get {
                return ResourceManager.GetString("ContactExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name ....
        /// </summary>
        public static string ContactNameLabel {
            get {
                return ResourceManager.GetString("ContactNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no contact with that id. Id: {0}.
        /// </summary>
        public static string ContactNotExists {
            get {
                return ResourceManager.GetString("ContactNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no contact type with that id. Id: {0}.
        /// </summary>
        public static string ContactTypeNotExists {
            get {
                return ResourceManager.GetString("ContactTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contact.
        /// </summary>
        public static string CreateContact {
            get {
                return ResourceManager.GetString("CreateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Date Ascending.
        /// </summary>
        public static string DateAscending {
            get {
                return ResourceManager.GetString("DateAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Date Descending.
        /// </summary>
        public static string DateDescending {
            get {
                return ResourceManager.GetString("DateDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        public static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete contact?.
        /// </summary>
        public static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contact.
        /// </summary>
        public static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is very large..
        /// </summary>
        public static string FieldVeryLarge {
            get {
                return ResourceManager.GetString("FieldVeryLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number Invalid.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:     -     -    .
        /// </summary>
        public static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RanKing.
        /// </summary>
        public static string RanKing {
            get {
                return ResourceManager.GetString("RanKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no reservation with that id. Id: {0}.
        /// </summary>
        public static string ReservationNotExists {
            get {
                return ResourceManager.GetString("ReservationNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact List.
        /// </summary>
        public static string TitleContactList {
            get {
                return ResourceManager.GetString("TitleContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Reservation.
        /// </summary>
        public static string TitleCreateReservation {
            get {
                return ResourceManager.GetString("TitleCreateReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reservation.
        /// </summary>
        public static string TitleEditReservation {
            get {
                return ResourceManager.GetString("TitleEditReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations List.
        /// </summary>
        public static string TitleReservationsList {
            get {
                return ResourceManager.GetString("TitleReservationsList", resourceCulture);
            }
        }
    }
}
